<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ArchDiver.Core\ArchDiver.Core.csproj" />
    <ProjectReference Include="..\ArchDiver.Shared\ArchDiver.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Tomlyn" Version="2.3.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
