<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TreeSitter.DotNet" Version="1.1.1" />
    <PackageReference Include="TreeSitterLanguagePack" Version="1.8.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ArchDiver.Core\ArchDiver.Core.csproj" />
  </ItemGroup>

</Project>
